/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.jdbc;

import com.mybillr.app.dao.*;
import com.mybillr.app.factory.*;
import java.util.Date;
import com.mybillr.app.dto.*;
import com.mybillr.app.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class EmailSentDaoImpl extends AbstractDAO implements EmailSentDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id, from, to, subject, message, sent_on FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( id, from, to, subject, message, sent_on ) VALUES ( ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id = ?, from = ?, to = ?, subject = ?, message = ?, sent_on = ? WHERE id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id = ?";

	/** 
	 * Index of column id
	 */
	protected static final int COLUMN_ID = 1;

	/** 
	 * Index of column from
	 */
	protected static final int COLUMN_FROM = 2;

	/** 
	 * Index of column to
	 */
	protected static final int COLUMN_TO = 3;

	/** 
	 * Index of column subject
	 */
	protected static final int COLUMN_SUBJECT = 4;

	/** 
	 * Index of column message
	 */
	protected static final int COLUMN_MESSAGE = 5;

	/** 
	 * Index of column sent_on
	 */
	protected static final int COLUMN_SENT_ON = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column id
	 */
	protected static final int PK_COLUMN_ID = 1;

	/** 
	 * Inserts a new row in the email_sent table.
	 */
	public EmailSentPk insert(EmailSent dto) throws EmailSentDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "id" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isFromModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "from" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isToModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "to" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isSubjectModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "subject" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isMessageModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "message" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isSentOnModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "sent_on" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString(), Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			if (dto.isIdModified()) {
				stmt.setInt( index++, dto.getId() );
			}
		
			if (dto.isFromModified()) {
				stmt.setString( index++, dto.getFrom() );
			}
		
			if (dto.isToModified()) {
				stmt.setString( index++, dto.getTo() );
			}
		
			if (dto.isSubjectModified()) {
				stmt.setString( index++, dto.getSubject() );
			}
		
			if (dto.isMessageModified()) {
				stmt.setString( index++, dto.getMessage() );
			}
		
			if (dto.isSentOnModified()) {
				stmt.setTimestamp(index++, dto.getSentOn()==null ? null : new java.sql.Timestamp( dto.getSentOn().getTime() ) );
			}
		
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setId( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmailSentDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the email_sent table.
	 */
	public void update(EmailSentPk pk, EmailSent dto) throws EmailSentDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "id=?" );
				modified=true;
			}
		
			if (dto.isFromModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "from=?" );
				modified=true;
			}
		
			if (dto.isToModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "to=?" );
				modified=true;
			}
		
			if (dto.isSubjectModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "subject=?" );
				modified=true;
			}
		
			if (dto.isMessageModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "message=?" );
				modified=true;
			}
		
			if (dto.isSentOnModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "sent_on=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE id=?" );
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdModified()) {
				stmt.setInt( index++, dto.getId() );
			}
		
			if (dto.isFromModified()) {
				stmt.setString( index++, dto.getFrom() );
			}
		
			if (dto.isToModified()) {
				stmt.setString( index++, dto.getTo() );
			}
		
			if (dto.isSubjectModified()) {
				stmt.setString( index++, dto.getSubject() );
			}
		
			if (dto.isMessageModified()) {
				stmt.setString( index++, dto.getMessage() );
			}
		
			if (dto.isSentOnModified()) {
				stmt.setTimestamp(index++, dto.getSentOn()==null ? null : new java.sql.Timestamp( dto.getSentOn().getTime() ) );
			}
		
			stmt.setInt( index++, pk.getId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmailSentDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the email_sent table.
	 */
	public void delete(EmailSentPk pk) throws EmailSentDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmailSentDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the email_sent table that matches the specified primary-key value.
	 */
	public EmailSent findByPrimaryKey(EmailSentPk pk) throws EmailSentDaoException
	{
		return findByPrimaryKey( pk.getId() );
	}

	/** 
	 * Returns all rows from the email_sent table that match the criteria 'id = :id'.
	 */
	public EmailSent findByPrimaryKey(int id) throws EmailSentDaoException
	{
		EmailSent ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id = ?", new Object[] {  new Integer(id) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the email_sent table that match the criteria ''.
	 */
	public EmailSent[] findAll() throws EmailSentDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id", null );
	}

	/** 
	 * Returns all rows from the email_sent table that match the criteria 'id = :id'.
	 */
	public EmailSent[] findWhereIdEquals(int id) throws EmailSentDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id = ? ORDER BY id", new Object[] {  new Integer(id) } );
	}

	/** 
	 * Returns all rows from the email_sent table that match the criteria 'from = :from'.
	 */
	public EmailSent[] findWhereFromEquals(String from) throws EmailSentDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE from = ? ORDER BY from", new Object[] { from } );
	}

	/** 
	 * Returns all rows from the email_sent table that match the criteria 'to = :to'.
	 */
	public EmailSent[] findWhereToEquals(String to) throws EmailSentDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE to = ? ORDER BY to", new Object[] { to } );
	}

	/** 
	 * Returns all rows from the email_sent table that match the criteria 'subject = :subject'.
	 */
	public EmailSent[] findWhereSubjectEquals(String subject) throws EmailSentDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE subject = ? ORDER BY subject", new Object[] { subject } );
	}

	/** 
	 * Returns all rows from the email_sent table that match the criteria 'message = :message'.
	 */
	public EmailSent[] findWhereMessageEquals(String message) throws EmailSentDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE message = ? ORDER BY message", new Object[] { message } );
	}

	/** 
	 * Returns all rows from the email_sent table that match the criteria 'sent_on = :sentOn'.
	 */
	public EmailSent[] findWhereSentOnEquals(Date sentOn) throws EmailSentDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE sent_on = ? ORDER BY sent_on", new Object[] { sentOn==null ? null : new java.sql.Timestamp( sentOn.getTime() ) } );
	}

	/**
	 * Method 'EmailSentDaoImpl'
	 * 
	 */
	public EmailSentDaoImpl()
	{
	}

	/**
	 * Method 'EmailSentDaoImpl'
	 * 
	 * @param userConn
	 */
	public EmailSentDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "email_sent";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected EmailSent fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			EmailSent dto = new EmailSent();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected EmailSent[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			EmailSent dto = new EmailSent();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		EmailSent ret[] = new EmailSent[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(EmailSent dto, ResultSet rs) throws SQLException
	{
		dto.setId( rs.getInt( COLUMN_ID ) );
		dto.setFrom( rs.getString( COLUMN_FROM ) );
		dto.setTo( rs.getString( COLUMN_TO ) );
		dto.setSubject( rs.getString( COLUMN_SUBJECT ) );
		dto.setMessage( rs.getString( COLUMN_MESSAGE ) );
		dto.setSentOn( rs.getTimestamp(COLUMN_SENT_ON ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(EmailSent dto)
	{
		dto.setIdModified( false );
		dto.setFromModified( false );
		dto.setToModified( false );
		dto.setSubjectModified( false );
		dto.setMessageModified( false );
		dto.setSentOnModified( false );
	}

	/** 
	 * Returns all rows from the email_sent table that match the specified arbitrary SQL statement
	 */
	public EmailSent[] findByDynamicSelect(String sql, Object[] sqlParams) throws EmailSentDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmailSentDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the email_sent table that match the specified arbitrary SQL statement
	 */
	public EmailSent[] findByDynamicWhere(String sql, Object[] sqlParams) throws EmailSentDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new EmailSentDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
