/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.jdbc;

import com.mybillr.app.dao.*;
import com.mybillr.app.factory.*;
import com.mybillr.app.dto.*;
import com.mybillr.app.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class SharedBillDaoImpl extends AbstractDAO implements SharedBillDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id, title, participants, paid_by, items FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( id, title, participants, paid_by, items ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id = ?, title = ?, participants = ?, paid_by = ?, items = ? WHERE id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id = ?";

	/** 
	 * Index of column id
	 */
	protected static final int COLUMN_ID = 1;

	/** 
	 * Index of column title
	 */
	protected static final int COLUMN_TITLE = 2;

	/** 
	 * Index of column participants
	 */
	protected static final int COLUMN_PARTICIPANTS = 3;

	/** 
	 * Index of column paid_by
	 */
	protected static final int COLUMN_PAID_BY = 4;

	/** 
	 * Index of column items
	 */
	protected static final int COLUMN_ITEMS = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column id
	 */
	protected static final int PK_COLUMN_ID = 1;

	/** 
	 * Inserts a new row in the shared_bill table.
	 */
	public SharedBillPk insert(SharedBill dto) throws SharedBillDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			StringBuffer values = new StringBuffer();
			sql.append( "INSERT INTO " + getTableName() + " (" );
			int modifiedCount = 0;
			if (dto.isIdModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "id" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isTitleModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "title" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isParticipantsModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "participants" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isPaidByModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "paid_by" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (dto.isItemsModified()) {
				if (modifiedCount>0) {
					sql.append( ", " );
					values.append( ", " );
				}
		
				sql.append( "items" );
				values.append( "?" );
				modifiedCount++;
			}
		
			if (modifiedCount==0) {
				// nothing to insert
				throw new IllegalStateException( "Nothing to insert" );
			}
		
			sql.append( ") VALUES (" );
			sql.append( values );
			sql.append( ")" );
			stmt = conn.prepareStatement( sql.toString(), Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			if (dto.isIdModified()) {
				stmt.setInt( index++, dto.getId() );
			}
		
			if (dto.isTitleModified()) {
				stmt.setString( index++, dto.getTitle() );
			}
		
			if (dto.isParticipantsModified()) {
				stmt.setString( index++, dto.getParticipants() );
			}
		
			if (dto.isPaidByModified()) {
				stmt.setString( index++, dto.getPaidBy() );
			}
		
			if (dto.isItemsModified()) {
				stmt.setString( index++, dto.getItems() );
			}
		
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setId( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SharedBillDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the shared_bill table.
	 */
	public void update(SharedBillPk pk, SharedBill dto) throws SharedBillDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			StringBuffer sql = new StringBuffer();
			sql.append( "UPDATE " + getTableName() + " SET " );
			boolean modified = false;
			if (dto.isIdModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "id=?" );
				modified=true;
			}
		
			if (dto.isTitleModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "title=?" );
				modified=true;
			}
		
			if (dto.isParticipantsModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "participants=?" );
				modified=true;
			}
		
			if (dto.isPaidByModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "paid_by=?" );
				modified=true;
			}
		
			if (dto.isItemsModified()) {
				if (modified) {
					sql.append( ", " );
				}
		
				sql.append( "items=?" );
				modified=true;
			}
		
			if (!modified) {
				// nothing to update
				return;
			}
		
			sql.append( " WHERE id=?" );
			System.out.println( "Executing " + sql.toString() + " with values: " + dto );
			stmt = conn.prepareStatement( sql.toString() );
			int index = 1;
			if (dto.isIdModified()) {
				stmt.setInt( index++, dto.getId() );
			}
		
			if (dto.isTitleModified()) {
				stmt.setString( index++, dto.getTitle() );
			}
		
			if (dto.isParticipantsModified()) {
				stmt.setString( index++, dto.getParticipants() );
			}
		
			if (dto.isPaidByModified()) {
				stmt.setString( index++, dto.getPaidBy() );
			}
		
			if (dto.isItemsModified()) {
				stmt.setString( index++, dto.getItems() );
			}
		
			stmt.setInt( index++, pk.getId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SharedBillDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the shared_bill table.
	 */
	public void delete(SharedBillPk pk) throws SharedBillDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SharedBillDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the shared_bill table that matches the specified primary-key value.
	 */
	public SharedBill findByPrimaryKey(SharedBillPk pk) throws SharedBillDaoException
	{
		return findByPrimaryKey( pk.getId() );
	}

	/** 
	 * Returns all rows from the shared_bill table that match the criteria 'id = :id'.
	 */
	public SharedBill findByPrimaryKey(int id) throws SharedBillDaoException
	{
		SharedBill ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id = ?", new Object[] {  new Integer(id) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the shared_bill table that match the criteria ''.
	 */
	public SharedBill[] findAll() throws SharedBillDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id", null );
	}

	/** 
	 * Returns all rows from the shared_bill table that match the criteria 'id = :id'.
	 */
	public SharedBill[] findWhereIdEquals(int id) throws SharedBillDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id = ? ORDER BY id", new Object[] {  new Integer(id) } );
	}

	/** 
	 * Returns all rows from the shared_bill table that match the criteria 'title = :title'.
	 */
	public SharedBill[] findWhereTitleEquals(String title) throws SharedBillDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE title = ? ORDER BY title", new Object[] { title } );
	}

	/** 
	 * Returns all rows from the shared_bill table that match the criteria 'participants = :participants'.
	 */
	public SharedBill[] findWhereParticipantsEquals(String participants) throws SharedBillDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE participants = ? ORDER BY participants", new Object[] { participants } );
	}

	/** 
	 * Returns all rows from the shared_bill table that match the criteria 'paid_by = :paidBy'.
	 */
	public SharedBill[] findWherePaidByEquals(String paidBy) throws SharedBillDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE paid_by = ? ORDER BY paid_by", new Object[] { paidBy } );
	}

	/** 
	 * Returns all rows from the shared_bill table that match the criteria 'items = :items'.
	 */
	public SharedBill[] findWhereItemsEquals(String items) throws SharedBillDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE items = ? ORDER BY items", new Object[] { items } );
	}

	/**
	 * Method 'SharedBillDaoImpl'
	 * 
	 */
	public SharedBillDaoImpl()
	{
	}

	/**
	 * Method 'SharedBillDaoImpl'
	 * 
	 * @param userConn
	 */
	public SharedBillDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "shared_bill";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected SharedBill fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			SharedBill dto = new SharedBill();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected SharedBill[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			SharedBill dto = new SharedBill();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		SharedBill ret[] = new SharedBill[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(SharedBill dto, ResultSet rs) throws SQLException
	{
		dto.setId( rs.getInt( COLUMN_ID ) );
		dto.setTitle( rs.getString( COLUMN_TITLE ) );
		dto.setParticipants( rs.getString( COLUMN_PARTICIPANTS ) );
		dto.setPaidBy( rs.getString( COLUMN_PAID_BY ) );
		dto.setItems( rs.getString( COLUMN_ITEMS ) );
		reset(dto);
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(SharedBill dto)
	{
		dto.setIdModified( false );
		dto.setTitleModified( false );
		dto.setParticipantsModified( false );
		dto.setPaidByModified( false );
		dto.setItemsModified( false );
	}

	/** 
	 * Returns all rows from the shared_bill table that match the specified arbitrary SQL statement
	 */
	public SharedBill[] findByDynamicSelect(String sql, Object[] sqlParams) throws SharedBillDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SharedBillDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the shared_bill table that match the specified arbitrary SQL statement
	 */
	public SharedBill[] findByDynamicWhere(String sql, Object[] sqlParams) throws SharedBillDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new SharedBillDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
