/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dao;

import com.mybillr.app.dto.*;
import com.mybillr.app.exceptions.*;

public interface ItemizedBillDao
{
	/** 
	 * Inserts a new row in the itemized_bill table.
	 */
	public ItemizedBillPk insert(ItemizedBill dto) throws ItemizedBillDaoException;

	/** 
	 * Updates a single row in the itemized_bill table.
	 */
	public void update(ItemizedBillPk pk, ItemizedBill dto) throws ItemizedBillDaoException;

	/** 
	 * Deletes a single row in the itemized_bill table.
	 */
	public void delete(ItemizedBillPk pk) throws ItemizedBillDaoException;

	/** 
	 * Returns the rows from the itemized_bill table that matches the specified primary-key value.
	 */
	public ItemizedBill findByPrimaryKey(ItemizedBillPk pk) throws ItemizedBillDaoException;

	/** 
	 * Returns all rows from the itemized_bill table that match the criteria 'id = :id'.
	 */
	public ItemizedBill findByPrimaryKey(int id) throws ItemizedBillDaoException;

	/** 
	 * Returns all rows from the itemized_bill table that match the criteria ''.
	 */
	public ItemizedBill[] findAll() throws ItemizedBillDaoException;

	/** 
	 * Returns all rows from the itemized_bill table that match the criteria 'id = :id'.
	 */
	public ItemizedBill[] findWhereIdEquals(int id) throws ItemizedBillDaoException;

	/** 
	 * Returns all rows from the itemized_bill table that match the criteria 'paid_by = :paidBy'.
	 */
	public ItemizedBill[] findWherePaidByEquals(String paidBy) throws ItemizedBillDaoException;

	/** 
	 * Returns all rows from the itemized_bill table that match the criteria 'items = :items'.
	 */
	public ItemizedBill[] findWhereItemsEquals(String items) throws ItemizedBillDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the itemized_bill table that match the specified arbitrary SQL statement
	 */
	public ItemizedBill[] findByDynamicSelect(String sql, Object[] sqlParams) throws ItemizedBillDaoException;

	/** 
	 * Returns all rows from the itemized_bill table that match the specified arbitrary SQL statement
	 */
	public ItemizedBill[] findByDynamicWhere(String sql, Object[] sqlParams) throws ItemizedBillDaoException;

}
