/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mybillr.db.dao.Table1Dao;
import com.mybillr.db.dto.Table1;
import com.mybillr.db.exceptions.Table1DaoException;
import com.mybillr.db.factory.Table1DaoFactory;

public class Table1DaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdEquals(0);
		// findWhereNameEquals("");
		// findWhereSymbolEquals("");
		// findWhereRateEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			Table1Dao _dao = getTable1Dao();
			Table1 _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdEquals'
	 * 
	 * @param id
	 */
	public static void findWhereIdEquals(int id)
	{
		try {
			Table1Dao _dao = getTable1Dao();
			Table1 _result[] = _dao.findWhereIdEquals(id);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNameEquals'
	 * 
	 * @param name
	 */
	public static void findWhereNameEquals(String name)
	{
		try {
			Table1Dao _dao = getTable1Dao();
			Table1 _result[] = _dao.findWhereNameEquals(name);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSymbolEquals'
	 * 
	 * @param symbol
	 */
	public static void findWhereSymbolEquals(String symbol)
	{
		try {
			Table1Dao _dao = getTable1Dao();
			Table1 _result[] = _dao.findWhereSymbolEquals(symbol);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereRateEquals'
	 * 
	 * @param rate
	 */
	public static void findWhereRateEquals(long rate)
	{
		try {
			Table1Dao _dao = getTable1Dao();
			Table1 _result[] = _dao.findWhereRateEquals(rate);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getTable1Dao'
	 * 
	 * @return Table1Dao
	 */
	public static Table1Dao getTable1Dao()
	{
		return Table1DaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Table1 dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getId() );
		buf.append( ", " );
		buf.append( dto.getName() );
		buf.append( ", " );
		buf.append( dto.getSymbol() );
		buf.append( ", " );
		buf.append( dto.getRate() );
		System.out.println( buf.toString() );
	}

}
