/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import com.mybillr.app.dao.*;
import com.mybillr.app.factory.*;
import com.mybillr.app.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Currencies implements Serializable
{
	/** 
	 * This attribute maps to the column id in the currencies table.
	 */
	protected short id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column code in the currencies table.
	 */
	protected String code;

	/** 
	 * This attribute represents whether the attribute code has been modified since being read from the database.
	 */
	protected boolean codeModified = false;

	/** 
	 * This attribute maps to the column currency in the currencies table.
	 */
	protected String currency;

	/** 
	 * This attribute represents whether the attribute currency has been modified since being read from the database.
	 */
	protected boolean currencyModified = false;

	/** 
	 * This attribute maps to the column country in the currencies table.
	 */
	protected String country;

	/** 
	 * This attribute represents whether the attribute country has been modified since being read from the database.
	 */
	protected boolean countryModified = false;

	/**
	 * Method 'Currencies'
	 * 
	 */
	public Currencies()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return short
	 */
	public short getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(short id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getCode'
	 * 
	 * @return String
	 */
	public String getCode()
	{
		return code;
	}

	/**
	 * Method 'setCode'
	 * 
	 * @param code
	 */
	public void setCode(String code)
	{
		this.code = code;
		this.codeModified = true;
	}

	/** 
	 * Sets the value of codeModified
	 */
	public void setCodeModified(boolean codeModified)
	{
		this.codeModified = codeModified;
	}

	/** 
	 * Gets the value of codeModified
	 */
	public boolean isCodeModified()
	{
		return codeModified;
	}

	/**
	 * Method 'getCurrency'
	 * 
	 * @return String
	 */
	public String getCurrency()
	{
		return currency;
	}

	/**
	 * Method 'setCurrency'
	 * 
	 * @param currency
	 */
	public void setCurrency(String currency)
	{
		this.currency = currency;
		this.currencyModified = true;
	}

	/** 
	 * Sets the value of currencyModified
	 */
	public void setCurrencyModified(boolean currencyModified)
	{
		this.currencyModified = currencyModified;
	}

	/** 
	 * Gets the value of currencyModified
	 */
	public boolean isCurrencyModified()
	{
		return currencyModified;
	}

	/**
	 * Method 'getCountry'
	 * 
	 * @return String
	 */
	public String getCountry()
	{
		return country;
	}

	/**
	 * Method 'setCountry'
	 * 
	 * @param country
	 */
	public void setCountry(String country)
	{
		this.country = country;
		this.countryModified = true;
	}

	/** 
	 * Sets the value of countryModified
	 */
	public void setCountryModified(boolean countryModified)
	{
		this.countryModified = countryModified;
	}

	/** 
	 * Gets the value of countryModified
	 */
	public boolean isCountryModified()
	{
		return countryModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Currencies)) {
			return false;
		}
		
		final Currencies _cast = (Currencies) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (code == null ? _cast.code != code : !code.equals( _cast.code )) {
			return false;
		}
		
		if (codeModified != _cast.codeModified) {
			return false;
		}
		
		if (currency == null ? _cast.currency != currency : !currency.equals( _cast.currency )) {
			return false;
		}
		
		if (currencyModified != _cast.currencyModified) {
			return false;
		}
		
		if (country == null ? _cast.country != country : !country.equals( _cast.country )) {
			return false;
		}
		
		if (countryModified != _cast.countryModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		if (code != null) {
			_hashCode = 29 * _hashCode + code.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (codeModified ? 1 : 0);
		if (currency != null) {
			_hashCode = 29 * _hashCode + currency.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (currencyModified ? 1 : 0);
		if (country != null) {
			_hashCode = 29 * _hashCode + country.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (countryModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CurrenciesPk
	 */
	public CurrenciesPk createPk()
	{
		return new CurrenciesPk(id, code);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.Currencies: " );
		ret.append( "id=" + id );
		ret.append( ", code=" + code );
		ret.append( ", currency=" + currency );
		ret.append( ", country=" + country );
		return ret.toString();
	}

}
