/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the currencies table.
 */
public class CurrenciesPk implements Serializable
{
	protected short id;

	protected String code;

	/** 
	 * This attribute represents whether the primitive attribute id is null.
	 */
	protected boolean idNull;

	/** 
	 * Sets the value of id
	 */
	public void setId(short id)
	{
		this.id = id;
	}

	/** 
	 * Gets the value of id
	 */
	public short getId()
	{
		return id;
	}

	/** 
	 * Sets the value of code
	 */
	public void setCode(String code)
	{
		this.code = code;
	}

	/** 
	 * Gets the value of code
	 */
	public String getCode()
	{
		return code;
	}

	/**
	 * Method 'CurrenciesPk'
	 * 
	 */
	public CurrenciesPk()
	{
	}

	/**
	 * Method 'CurrenciesPk'
	 * 
	 * @param id
	 * @param code
	 */
	public CurrenciesPk(final short id, final String code)
	{
		this.id = id;
		this.code = code;
	}

	/** 
	 * Sets the value of idNull
	 */
	public void setIdNull(boolean idNull)
	{
		this.idNull = idNull;
	}

	/** 
	 * Gets the value of idNull
	 */
	public boolean isIdNull()
	{
		return idNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CurrenciesPk)) {
			return false;
		}
		
		final CurrenciesPk _cast = (CurrenciesPk) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (code == null ? _cast.code != code : !code.equals( _cast.code )) {
			return false;
		}
		
		if (idNull != _cast.idNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + (int) id;
		if (code != null) {
			_hashCode = 29 * _hashCode + code.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.CurrenciesPk: " );
		ret.append( "id=" + id );
		ret.append( ", code=" + code );
		return ret.toString();
	}

}
