/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import com.mybillr.app.dao.*;
import com.mybillr.app.factory.*;
import com.mybillr.app.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Friends implements Serializable
{
	/** 
	 * This attribute maps to the column user_id in the friends table.
	 */
	protected int userId;

	/** 
	 * This attribute represents whether the attribute userId has been modified since being read from the database.
	 */
	protected boolean userIdModified = false;

	/** 
	 * This attribute maps to the column friend_id in the friends table.
	 */
	protected int friendId;

	/** 
	 * This attribute represents whether the attribute friendId has been modified since being read from the database.
	 */
	protected boolean friendIdModified = false;

	/**
	 * Method 'Friends'
	 * 
	 */
	public Friends()
	{
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return int
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
		this.userIdModified = true;
	}

	/** 
	 * Sets the value of userIdModified
	 */
	public void setUserIdModified(boolean userIdModified)
	{
		this.userIdModified = userIdModified;
	}

	/** 
	 * Gets the value of userIdModified
	 */
	public boolean isUserIdModified()
	{
		return userIdModified;
	}

	/**
	 * Method 'getFriendId'
	 * 
	 * @return int
	 */
	public int getFriendId()
	{
		return friendId;
	}

	/**
	 * Method 'setFriendId'
	 * 
	 * @param friendId
	 */
	public void setFriendId(int friendId)
	{
		this.friendId = friendId;
		this.friendIdModified = true;
	}

	/** 
	 * Sets the value of friendIdModified
	 */
	public void setFriendIdModified(boolean friendIdModified)
	{
		this.friendIdModified = friendIdModified;
	}

	/** 
	 * Gets the value of friendIdModified
	 */
	public boolean isFriendIdModified()
	{
		return friendIdModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Friends)) {
			return false;
		}
		
		final Friends _cast = (Friends) _other;
		if (userId != _cast.userId) {
			return false;
		}
		
		if (userIdModified != _cast.userIdModified) {
			return false;
		}
		
		if (friendId != _cast.friendId) {
			return false;
		}
		
		if (friendIdModified != _cast.friendIdModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + (userIdModified ? 1 : 0);
		_hashCode = 29 * _hashCode + friendId;
		_hashCode = 29 * _hashCode + (friendIdModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return FriendsPk
	 */
	public FriendsPk createPk()
	{
		return new FriendsPk(userId, friendId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.Friends: " );
		ret.append( "userId=" + userId );
		ret.append( ", friendId=" + friendId );
		return ret.toString();
	}

}
