/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the groups table.
 */
public class GroupsPk implements Serializable
{
	protected int id;

	protected String name;

	protected int memberId;

	/** 
	 * This attribute represents whether the primitive attribute id is null.
	 */
	protected boolean idNull;

	/** 
	 * This attribute represents whether the primitive attribute memberId is null.
	 */
	protected boolean memberIdNull;

	/** 
	 * Sets the value of id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/** 
	 * Gets the value of id
	 */
	public int getId()
	{
		return id;
	}

	/** 
	 * Sets the value of name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/** 
	 * Gets the value of name
	 */
	public String getName()
	{
		return name;
	}

	/** 
	 * Sets the value of memberId
	 */
	public void setMemberId(int memberId)
	{
		this.memberId = memberId;
	}

	/** 
	 * Gets the value of memberId
	 */
	public int getMemberId()
	{
		return memberId;
	}

	/**
	 * Method 'GroupsPk'
	 * 
	 */
	public GroupsPk()
	{
	}

	/**
	 * Method 'GroupsPk'
	 * 
	 * @param id
	 * @param name
	 * @param memberId
	 */
	public GroupsPk(final int id, final String name, final int memberId)
	{
		this.id = id;
		this.name = name;
		this.memberId = memberId;
	}

	/** 
	 * Sets the value of idNull
	 */
	public void setIdNull(boolean idNull)
	{
		this.idNull = idNull;
	}

	/** 
	 * Gets the value of idNull
	 */
	public boolean isIdNull()
	{
		return idNull;
	}

	/** 
	 * Sets the value of memberIdNull
	 */
	public void setMemberIdNull(boolean memberIdNull)
	{
		this.memberIdNull = memberIdNull;
	}

	/** 
	 * Gets the value of memberIdNull
	 */
	public boolean isMemberIdNull()
	{
		return memberIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof GroupsPk)) {
			return false;
		}
		
		final GroupsPk _cast = (GroupsPk) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (memberId != _cast.memberId) {
			return false;
		}
		
		if (idNull != _cast.idNull) {
			return false;
		}
		
		if (memberIdNull != _cast.memberIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		_hashCode = 29 * _hashCode + memberId;
		_hashCode = 29 * _hashCode + (idNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (memberIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.GroupsPk: " );
		ret.append( "id=" + id );
		ret.append( ", name=" + name );
		ret.append( ", memberId=" + memberId );
		return ret.toString();
	}

}
