/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import com.mybillr.app.dao.*;
import com.mybillr.app.factory.*;
import com.mybillr.app.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Groups implements Serializable
{
	/** 
	 * This attribute maps to the column id in the groups table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column name in the groups table.
	 */
	protected String name;

	/** 
	 * This attribute represents whether the attribute name has been modified since being read from the database.
	 */
	protected boolean nameModified = false;

	/** 
	 * This attribute maps to the column member_id in the groups table.
	 */
	protected int memberId;

	/** 
	 * This attribute represents whether the attribute memberId has been modified since being read from the database.
	 */
	protected boolean memberIdModified = false;

	/**
	 * Method 'Groups'
	 * 
	 */
	public Groups()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
		this.nameModified = true;
	}

	/** 
	 * Sets the value of nameModified
	 */
	public void setNameModified(boolean nameModified)
	{
		this.nameModified = nameModified;
	}

	/** 
	 * Gets the value of nameModified
	 */
	public boolean isNameModified()
	{
		return nameModified;
	}

	/**
	 * Method 'getMemberId'
	 * 
	 * @return int
	 */
	public int getMemberId()
	{
		return memberId;
	}

	/**
	 * Method 'setMemberId'
	 * 
	 * @param memberId
	 */
	public void setMemberId(int memberId)
	{
		this.memberId = memberId;
		this.memberIdModified = true;
	}

	/** 
	 * Sets the value of memberIdModified
	 */
	public void setMemberIdModified(boolean memberIdModified)
	{
		this.memberIdModified = memberIdModified;
	}

	/** 
	 * Gets the value of memberIdModified
	 */
	public boolean isMemberIdModified()
	{
		return memberIdModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Groups)) {
			return false;
		}
		
		final Groups _cast = (Groups) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (nameModified != _cast.nameModified) {
			return false;
		}
		
		if (memberId != _cast.memberId) {
			return false;
		}
		
		if (memberIdModified != _cast.memberIdModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nameModified ? 1 : 0);
		_hashCode = 29 * _hashCode + memberId;
		_hashCode = 29 * _hashCode + (memberIdModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return GroupsPk
	 */
	public GroupsPk createPk()
	{
		return new GroupsPk(id, name, memberId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.Groups: " );
		ret.append( "id=" + id );
		ret.append( ", name=" + name );
		ret.append( ", memberId=" + memberId );
		return ret.toString();
	}

}
