/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import com.mybillr.app.dao.*;
import com.mybillr.app.factory.*;
import com.mybillr.app.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ItemShare implements Serializable
{
	/** 
	 * This attribute maps to the column id in the item_share table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column item_id in the item_share table.
	 */
	protected int itemId;

	/** 
	 * This attribute represents whether the attribute itemId has been modified since being read from the database.
	 */
	protected boolean itemIdModified = false;

	/** 
	 * This attribute maps to the column user_id in the item_share table.
	 */
	protected int userId;

	/** 
	 * This attribute represents whether the attribute userId has been modified since being read from the database.
	 */
	protected boolean userIdModified = false;

	/** 
	 * This attribute maps to the column share in the item_share table.
	 */
	protected int share;

	/** 
	 * This attribute represents whether the attribute share has been modified since being read from the database.
	 */
	protected boolean shareModified = false;

	/**
	 * Method 'ItemShare'
	 * 
	 */
	public ItemShare()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getItemId'
	 * 
	 * @return int
	 */
	public int getItemId()
	{
		return itemId;
	}

	/**
	 * Method 'setItemId'
	 * 
	 * @param itemId
	 */
	public void setItemId(int itemId)
	{
		this.itemId = itemId;
		this.itemIdModified = true;
	}

	/** 
	 * Sets the value of itemIdModified
	 */
	public void setItemIdModified(boolean itemIdModified)
	{
		this.itemIdModified = itemIdModified;
	}

	/** 
	 * Gets the value of itemIdModified
	 */
	public boolean isItemIdModified()
	{
		return itemIdModified;
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return int
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
		this.userIdModified = true;
	}

	/** 
	 * Sets the value of userIdModified
	 */
	public void setUserIdModified(boolean userIdModified)
	{
		this.userIdModified = userIdModified;
	}

	/** 
	 * Gets the value of userIdModified
	 */
	public boolean isUserIdModified()
	{
		return userIdModified;
	}

	/**
	 * Method 'getShare'
	 * 
	 * @return int
	 */
	public int getShare()
	{
		return share;
	}

	/**
	 * Method 'setShare'
	 * 
	 * @param share
	 */
	public void setShare(int share)
	{
		this.share = share;
		this.shareModified = true;
	}

	/** 
	 * Sets the value of shareModified
	 */
	public void setShareModified(boolean shareModified)
	{
		this.shareModified = shareModified;
	}

	/** 
	 * Gets the value of shareModified
	 */
	public boolean isShareModified()
	{
		return shareModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ItemShare)) {
			return false;
		}
		
		final ItemShare _cast = (ItemShare) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (itemId != _cast.itemId) {
			return false;
		}
		
		if (itemIdModified != _cast.itemIdModified) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (userIdModified != _cast.userIdModified) {
			return false;
		}
		
		if (share != _cast.share) {
			return false;
		}
		
		if (shareModified != _cast.shareModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		_hashCode = 29 * _hashCode + itemId;
		_hashCode = 29 * _hashCode + (itemIdModified ? 1 : 0);
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + (userIdModified ? 1 : 0);
		_hashCode = 29 * _hashCode + share;
		_hashCode = 29 * _hashCode + (shareModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ItemSharePk
	 */
	public ItemSharePk createPk()
	{
		return new ItemSharePk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.ItemShare: " );
		ret.append( "id=" + id );
		ret.append( ", itemId=" + itemId );
		ret.append( ", userId=" + userId );
		ret.append( ", share=" + share );
		return ret.toString();
	}

}
