/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the ledger table.
 */
public class LedgerPk implements Serializable
{
	protected int id;

	protected int currency;

	/** 
	 * This attribute represents whether the primitive attribute id is null.
	 */
	protected boolean idNull;

	/** 
	 * This attribute represents whether the primitive attribute currency is null.
	 */
	protected boolean currencyNull;

	/** 
	 * Sets the value of id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/** 
	 * Gets the value of id
	 */
	public int getId()
	{
		return id;
	}

	/** 
	 * Sets the value of currency
	 */
	public void setCurrency(int currency)
	{
		this.currency = currency;
	}

	/** 
	 * Gets the value of currency
	 */
	public int getCurrency()
	{
		return currency;
	}

	/**
	 * Method 'LedgerPk'
	 * 
	 */
	public LedgerPk()
	{
	}

	/**
	 * Method 'LedgerPk'
	 * 
	 * @param id
	 * @param currency
	 */
	public LedgerPk(final int id, final int currency)
	{
		this.id = id;
		this.currency = currency;
	}

	/** 
	 * Sets the value of idNull
	 */
	public void setIdNull(boolean idNull)
	{
		this.idNull = idNull;
	}

	/** 
	 * Gets the value of idNull
	 */
	public boolean isIdNull()
	{
		return idNull;
	}

	/** 
	 * Sets the value of currencyNull
	 */
	public void setCurrencyNull(boolean currencyNull)
	{
		this.currencyNull = currencyNull;
	}

	/** 
	 * Gets the value of currencyNull
	 */
	public boolean isCurrencyNull()
	{
		return currencyNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof LedgerPk)) {
			return false;
		}
		
		final LedgerPk _cast = (LedgerPk) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (currency != _cast.currency) {
			return false;
		}
		
		if (idNull != _cast.idNull) {
			return false;
		}
		
		if (currencyNull != _cast.currencyNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + currency;
		_hashCode = 29 * _hashCode + (idNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (currencyNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.LedgerPk: " );
		ret.append( "id=" + id );
		ret.append( ", currency=" + currency );
		return ret.toString();
	}

}
