/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dao;

import com.mybillr.db.dto.*;
import com.mybillr.db.exceptions.*;

public interface Table1Dao
{
	/** 
	 * Inserts a new row in the table1 table.
	 */
	public Table1Pk insert(Table1 dto) throws Table1DaoException;

	/** 
	 * Updates a single row in the table1 table.
	 */
	public void update(Table1Pk pk, Table1 dto) throws Table1DaoException;

	/** 
	 * Deletes a single row in the table1 table.
	 */
	public void delete(Table1Pk pk) throws Table1DaoException;

	/** 
	 * Returns the rows from the table1 table that matches the specified primary-key value.
	 */
	public Table1 findByPrimaryKey(Table1Pk pk) throws Table1DaoException;

	/** 
	 * Returns all rows from the table1 table that match the criteria 'id = :id'.
	 */
	public Table1 findByPrimaryKey(int id) throws Table1DaoException;

	/** 
	 * Returns all rows from the table1 table that match the criteria ''.
	 */
	public Table1[] findAll() throws Table1DaoException;

	/** 
	 * Returns all rows from the table1 table that match the criteria 'id = :id'.
	 */
	public Table1[] findWhereIdEquals(int id) throws Table1DaoException;

	/** 
	 * Returns all rows from the table1 table that match the criteria 'name = :name'.
	 */
	public Table1[] findWhereNameEquals(String name) throws Table1DaoException;

	/** 
	 * Returns all rows from the table1 table that match the criteria 'symbol = :symbol'.
	 */
	public Table1[] findWhereSymbolEquals(String symbol) throws Table1DaoException;

	/** 
	 * Returns all rows from the table1 table that match the criteria 'rate = :rate'.
	 */
	public Table1[] findWhereRateEquals(long rate) throws Table1DaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the table1 table that match the specified arbitrary SQL statement
	 */
	public Table1[] findByDynamicSelect(String sql, Object[] sqlParams) throws Table1DaoException;

	/** 
	 * Returns all rows from the table1 table that match the specified arbitrary SQL statement
	 */
	public Table1[] findByDynamicWhere(String sql, Object[] sqlParams) throws Table1DaoException;

}
