/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import com.mybillr.app.dao.*;
import com.mybillr.app.factory.*;
import com.mybillr.app.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class BugReport implements Serializable
{
	/** 
	 * This attribute maps to the column id in the bug_report table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column title in the bug_report table.
	 */
	protected String title;

	/** 
	 * This attribute represents whether the attribute title has been modified since being read from the database.
	 */
	protected boolean titleModified = false;

	/** 
	 * This attribute maps to the column user_id in the bug_report table.
	 */
	protected int userId;

	/** 
	 * This attribute represents whether the attribute userId has been modified since being read from the database.
	 */
	protected boolean userIdModified = false;

	/** 
	 * This attribute maps to the column message in the bug_report table.
	 */
	protected String message;

	/** 
	 * This attribute represents whether the attribute message has been modified since being read from the database.
	 */
	protected boolean messageModified = false;

	/** 
	 * This attribute maps to the column reported_on in the bug_report table.
	 */
	protected Date reportedOn;

	/** 
	 * This attribute represents whether the attribute reportedOn has been modified since being read from the database.
	 */
	protected boolean reportedOnModified = false;

	/**
	 * Method 'BugReport'
	 * 
	 */
	public BugReport()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getTitle'
	 * 
	 * @return String
	 */
	public String getTitle()
	{
		return title;
	}

	/**
	 * Method 'setTitle'
	 * 
	 * @param title
	 */
	public void setTitle(String title)
	{
		this.title = title;
		this.titleModified = true;
	}

	/** 
	 * Sets the value of titleModified
	 */
	public void setTitleModified(boolean titleModified)
	{
		this.titleModified = titleModified;
	}

	/** 
	 * Gets the value of titleModified
	 */
	public boolean isTitleModified()
	{
		return titleModified;
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return int
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
		this.userIdModified = true;
	}

	/** 
	 * Sets the value of userIdModified
	 */
	public void setUserIdModified(boolean userIdModified)
	{
		this.userIdModified = userIdModified;
	}

	/** 
	 * Gets the value of userIdModified
	 */
	public boolean isUserIdModified()
	{
		return userIdModified;
	}

	/**
	 * Method 'getMessage'
	 * 
	 * @return String
	 */
	public String getMessage()
	{
		return message;
	}

	/**
	 * Method 'setMessage'
	 * 
	 * @param message
	 */
	public void setMessage(String message)
	{
		this.message = message;
		this.messageModified = true;
	}

	/** 
	 * Sets the value of messageModified
	 */
	public void setMessageModified(boolean messageModified)
	{
		this.messageModified = messageModified;
	}

	/** 
	 * Gets the value of messageModified
	 */
	public boolean isMessageModified()
	{
		return messageModified;
	}

	/**
	 * Method 'getReportedOn'
	 * 
	 * @return Date
	 */
	public Date getReportedOn()
	{
		return reportedOn;
	}

	/**
	 * Method 'setReportedOn'
	 * 
	 * @param reportedOn
	 */
	public void setReportedOn(Date reportedOn)
	{
		this.reportedOn = reportedOn;
		this.reportedOnModified = true;
	}

	/** 
	 * Sets the value of reportedOnModified
	 */
	public void setReportedOnModified(boolean reportedOnModified)
	{
		this.reportedOnModified = reportedOnModified;
	}

	/** 
	 * Gets the value of reportedOnModified
	 */
	public boolean isReportedOnModified()
	{
		return reportedOnModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof BugReport)) {
			return false;
		}
		
		final BugReport _cast = (BugReport) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (title == null ? _cast.title != title : !title.equals( _cast.title )) {
			return false;
		}
		
		if (titleModified != _cast.titleModified) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (userIdModified != _cast.userIdModified) {
			return false;
		}
		
		if (message == null ? _cast.message != message : !message.equals( _cast.message )) {
			return false;
		}
		
		if (messageModified != _cast.messageModified) {
			return false;
		}
		
		if (reportedOn == null ? _cast.reportedOn != reportedOn : !reportedOn.equals( _cast.reportedOn )) {
			return false;
		}
		
		if (reportedOnModified != _cast.reportedOnModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		if (title != null) {
			_hashCode = 29 * _hashCode + title.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (titleModified ? 1 : 0);
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + (userIdModified ? 1 : 0);
		if (message != null) {
			_hashCode = 29 * _hashCode + message.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (messageModified ? 1 : 0);
		if (reportedOn != null) {
			_hashCode = 29 * _hashCode + reportedOn.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (reportedOnModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return BugReportPk
	 */
	public BugReportPk createPk()
	{
		return new BugReportPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.BugReport: " );
		ret.append( "id=" + id );
		ret.append( ", title=" + title );
		ret.append( ", userId=" + userId );
		ret.append( ", message=" + message );
		ret.append( ", reportedOn=" + reportedOn );
		return ret.toString();
	}

}
