/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the friends table.
 */
public class FriendsPk implements Serializable
{
	protected int userId;

	protected int friendId;

	/** 
	 * This attribute represents whether the primitive attribute userId is null.
	 */
	protected boolean userIdNull;

	/** 
	 * This attribute represents whether the primitive attribute friendId is null.
	 */
	protected boolean friendIdNull;

	/** 
	 * Sets the value of userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
	}

	/** 
	 * Gets the value of userId
	 */
	public int getUserId()
	{
		return userId;
	}

	/** 
	 * Sets the value of friendId
	 */
	public void setFriendId(int friendId)
	{
		this.friendId = friendId;
	}

	/** 
	 * Gets the value of friendId
	 */
	public int getFriendId()
	{
		return friendId;
	}

	/**
	 * Method 'FriendsPk'
	 * 
	 */
	public FriendsPk()
	{
	}

	/**
	 * Method 'FriendsPk'
	 * 
	 * @param userId
	 * @param friendId
	 */
	public FriendsPk(final int userId, final int friendId)
	{
		this.userId = userId;
		this.friendId = friendId;
	}

	/** 
	 * Sets the value of userIdNull
	 */
	public void setUserIdNull(boolean userIdNull)
	{
		this.userIdNull = userIdNull;
	}

	/** 
	 * Gets the value of userIdNull
	 */
	public boolean isUserIdNull()
	{
		return userIdNull;
	}

	/** 
	 * Sets the value of friendIdNull
	 */
	public void setFriendIdNull(boolean friendIdNull)
	{
		this.friendIdNull = friendIdNull;
	}

	/** 
	 * Gets the value of friendIdNull
	 */
	public boolean isFriendIdNull()
	{
		return friendIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof FriendsPk)) {
			return false;
		}
		
		final FriendsPk _cast = (FriendsPk) _other;
		if (userId != _cast.userId) {
			return false;
		}
		
		if (friendId != _cast.friendId) {
			return false;
		}
		
		if (userIdNull != _cast.userIdNull) {
			return false;
		}
		
		if (friendIdNull != _cast.friendIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + userId;
		_hashCode = 29 * _hashCode + friendId;
		_hashCode = 29 * _hashCode + (userIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (friendIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.FriendsPk: " );
		ret.append( "userId=" + userId );
		ret.append( ", friendId=" + friendId );
		return ret.toString();
	}

}
