/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import com.mybillr.app.dao.*;
import com.mybillr.app.factory.*;
import com.mybillr.app.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Items implements Serializable
{
	/** 
	 * This attribute maps to the column id in the items table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column name in the items table.
	 */
	protected String name;

	/** 
	 * This attribute represents whether the attribute name has been modified since being read from the database.
	 */
	protected boolean nameModified = false;

	/** 
	 * This attribute maps to the column participant in the items table.
	 */
	protected String participant;

	/** 
	 * This attribute represents whether the attribute participant has been modified since being read from the database.
	 */
	protected boolean participantModified = false;

	/** 
	 * This attribute maps to the column price in the items table.
	 */
	protected long price;

	/** 
	 * This attribute represents whether the attribute price has been modified since being read from the database.
	 */
	protected boolean priceModified = false;

	/**
	 * Method 'Items'
	 * 
	 */
	public Items()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
		this.nameModified = true;
	}

	/** 
	 * Sets the value of nameModified
	 */
	public void setNameModified(boolean nameModified)
	{
		this.nameModified = nameModified;
	}

	/** 
	 * Gets the value of nameModified
	 */
	public boolean isNameModified()
	{
		return nameModified;
	}

	/**
	 * Method 'getParticipant'
	 * 
	 * @return String
	 */
	public String getParticipant()
	{
		return participant;
	}

	/**
	 * Method 'setParticipant'
	 * 
	 * @param participant
	 */
	public void setParticipant(String participant)
	{
		this.participant = participant;
		this.participantModified = true;
	}

	/** 
	 * Sets the value of participantModified
	 */
	public void setParticipantModified(boolean participantModified)
	{
		this.participantModified = participantModified;
	}

	/** 
	 * Gets the value of participantModified
	 */
	public boolean isParticipantModified()
	{
		return participantModified;
	}

	/**
	 * Method 'getPrice'
	 * 
	 * @return long
	 */
	public long getPrice()
	{
		return price;
	}

	/**
	 * Method 'setPrice'
	 * 
	 * @param price
	 */
	public void setPrice(long price)
	{
		this.price = price;
		this.priceModified = true;
	}

	/** 
	 * Sets the value of priceModified
	 */
	public void setPriceModified(boolean priceModified)
	{
		this.priceModified = priceModified;
	}

	/** 
	 * Gets the value of priceModified
	 */
	public boolean isPriceModified()
	{
		return priceModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Items)) {
			return false;
		}
		
		final Items _cast = (Items) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (nameModified != _cast.nameModified) {
			return false;
		}
		
		if (participant == null ? _cast.participant != participant : !participant.equals( _cast.participant )) {
			return false;
		}
		
		if (participantModified != _cast.participantModified) {
			return false;
		}
		
		if (price != _cast.price) {
			return false;
		}
		
		if (priceModified != _cast.priceModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nameModified ? 1 : 0);
		if (participant != null) {
			_hashCode = 29 * _hashCode + participant.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (participantModified ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) (price ^ (price >>> 32));
		_hashCode = 29 * _hashCode + (priceModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ItemsPk
	 */
	public ItemsPk createPk()
	{
		return new ItemsPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.Items: " );
		ret.append( "id=" + id );
		ret.append( ", name=" + name );
		ret.append( ", participant=" + participant );
		ret.append( ", price=" + price );
		return ret.toString();
	}

}
