/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import com.mybillr.app.dao.*;
import com.mybillr.app.factory.*;
import com.mybillr.app.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ItemizedBill implements Serializable
{
	/** 
	 * This attribute maps to the column id in the itemized_bill table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column paid_by in the itemized_bill table.
	 */
	protected String paidBy;

	/** 
	 * This attribute represents whether the attribute paidBy has been modified since being read from the database.
	 */
	protected boolean paidByModified = false;

	/** 
	 * This attribute maps to the column items in the itemized_bill table.
	 */
	protected String items;

	/** 
	 * This attribute represents whether the attribute items has been modified since being read from the database.
	 */
	protected boolean itemsModified = false;

	/**
	 * Method 'ItemizedBill'
	 * 
	 */
	public ItemizedBill()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getPaidBy'
	 * 
	 * @return String
	 */
	public String getPaidBy()
	{
		return paidBy;
	}

	/**
	 * Method 'setPaidBy'
	 * 
	 * @param paidBy
	 */
	public void setPaidBy(String paidBy)
	{
		this.paidBy = paidBy;
		this.paidByModified = true;
	}

	/** 
	 * Sets the value of paidByModified
	 */
	public void setPaidByModified(boolean paidByModified)
	{
		this.paidByModified = paidByModified;
	}

	/** 
	 * Gets the value of paidByModified
	 */
	public boolean isPaidByModified()
	{
		return paidByModified;
	}

	/**
	 * Method 'getItems'
	 * 
	 * @return String
	 */
	public String getItems()
	{
		return items;
	}

	/**
	 * Method 'setItems'
	 * 
	 * @param items
	 */
	public void setItems(String items)
	{
		this.items = items;
		this.itemsModified = true;
	}

	/** 
	 * Sets the value of itemsModified
	 */
	public void setItemsModified(boolean itemsModified)
	{
		this.itemsModified = itemsModified;
	}

	/** 
	 * Gets the value of itemsModified
	 */
	public boolean isItemsModified()
	{
		return itemsModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ItemizedBill)) {
			return false;
		}
		
		final ItemizedBill _cast = (ItemizedBill) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (paidBy == null ? _cast.paidBy != paidBy : !paidBy.equals( _cast.paidBy )) {
			return false;
		}
		
		if (paidByModified != _cast.paidByModified) {
			return false;
		}
		
		if (items == null ? _cast.items != items : !items.equals( _cast.items )) {
			return false;
		}
		
		if (itemsModified != _cast.itemsModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		if (paidBy != null) {
			_hashCode = 29 * _hashCode + paidBy.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (paidByModified ? 1 : 0);
		if (items != null) {
			_hashCode = 29 * _hashCode + items.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (itemsModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ItemizedBillPk
	 */
	public ItemizedBillPk createPk()
	{
		return new ItemizedBillPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.ItemizedBill: " );
		ret.append( "id=" + id );
		ret.append( ", paidBy=" + paidBy );
		ret.append( ", items=" + items );
		return ret.toString();
	}

}
