/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import com.mybillr.app.dao.*;
import com.mybillr.app.factory.*;
import com.mybillr.app.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Ledger implements Serializable
{
	/** 
	 * This attribute maps to the column id in the ledger table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column owed_by in the ledger table.
	 */
	protected int owedBy;

	/** 
	 * This attribute represents whether the attribute owedBy has been modified since being read from the database.
	 */
	protected boolean owedByModified = false;

	/** 
	 * This attribute maps to the column owes_to in the ledger table.
	 */
	protected int owesTo;

	/** 
	 * This attribute represents whether the attribute owesTo has been modified since being read from the database.
	 */
	protected boolean owesToModified = false;

	/** 
	 * This attribute maps to the column amount in the ledger table.
	 */
	protected int amount;

	/** 
	 * This attribute represents whether the attribute amount has been modified since being read from the database.
	 */
	protected boolean amountModified = false;

	/** 
	 * This attribute maps to the column currency in the ledger table.
	 */
	protected int currency;

	/** 
	 * This attribute represents whether the attribute currency has been modified since being read from the database.
	 */
	protected boolean currencyModified = false;

	/**
	 * Method 'Ledger'
	 * 
	 */
	public Ledger()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getOwedBy'
	 * 
	 * @return int
	 */
	public int getOwedBy()
	{
		return owedBy;
	}

	/**
	 * Method 'setOwedBy'
	 * 
	 * @param owedBy
	 */
	public void setOwedBy(int owedBy)
	{
		this.owedBy = owedBy;
		this.owedByModified = true;
	}

	/** 
	 * Sets the value of owedByModified
	 */
	public void setOwedByModified(boolean owedByModified)
	{
		this.owedByModified = owedByModified;
	}

	/** 
	 * Gets the value of owedByModified
	 */
	public boolean isOwedByModified()
	{
		return owedByModified;
	}

	/**
	 * Method 'getOwesTo'
	 * 
	 * @return int
	 */
	public int getOwesTo()
	{
		return owesTo;
	}

	/**
	 * Method 'setOwesTo'
	 * 
	 * @param owesTo
	 */
	public void setOwesTo(int owesTo)
	{
		this.owesTo = owesTo;
		this.owesToModified = true;
	}

	/** 
	 * Sets the value of owesToModified
	 */
	public void setOwesToModified(boolean owesToModified)
	{
		this.owesToModified = owesToModified;
	}

	/** 
	 * Gets the value of owesToModified
	 */
	public boolean isOwesToModified()
	{
		return owesToModified;
	}

	/**
	 * Method 'getAmount'
	 * 
	 * @return int
	 */
	public int getAmount()
	{
		return amount;
	}

	/**
	 * Method 'setAmount'
	 * 
	 * @param amount
	 */
	public void setAmount(int amount)
	{
		this.amount = amount;
		this.amountModified = true;
	}

	/** 
	 * Sets the value of amountModified
	 */
	public void setAmountModified(boolean amountModified)
	{
		this.amountModified = amountModified;
	}

	/** 
	 * Gets the value of amountModified
	 */
	public boolean isAmountModified()
	{
		return amountModified;
	}

	/**
	 * Method 'getCurrency'
	 * 
	 * @return int
	 */
	public int getCurrency()
	{
		return currency;
	}

	/**
	 * Method 'setCurrency'
	 * 
	 * @param currency
	 */
	public void setCurrency(int currency)
	{
		this.currency = currency;
		this.currencyModified = true;
	}

	/** 
	 * Sets the value of currencyModified
	 */
	public void setCurrencyModified(boolean currencyModified)
	{
		this.currencyModified = currencyModified;
	}

	/** 
	 * Gets the value of currencyModified
	 */
	public boolean isCurrencyModified()
	{
		return currencyModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Ledger)) {
			return false;
		}
		
		final Ledger _cast = (Ledger) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (owedBy != _cast.owedBy) {
			return false;
		}
		
		if (owedByModified != _cast.owedByModified) {
			return false;
		}
		
		if (owesTo != _cast.owesTo) {
			return false;
		}
		
		if (owesToModified != _cast.owesToModified) {
			return false;
		}
		
		if (amount != _cast.amount) {
			return false;
		}
		
		if (amountModified != _cast.amountModified) {
			return false;
		}
		
		if (currency != _cast.currency) {
			return false;
		}
		
		if (currencyModified != _cast.currencyModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		_hashCode = 29 * _hashCode + owedBy;
		_hashCode = 29 * _hashCode + (owedByModified ? 1 : 0);
		_hashCode = 29 * _hashCode + owesTo;
		_hashCode = 29 * _hashCode + (owesToModified ? 1 : 0);
		_hashCode = 29 * _hashCode + amount;
		_hashCode = 29 * _hashCode + (amountModified ? 1 : 0);
		_hashCode = 29 * _hashCode + currency;
		_hashCode = 29 * _hashCode + (currencyModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return LedgerPk
	 */
	public LedgerPk createPk()
	{
		return new LedgerPk(id, currency);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.Ledger: " );
		ret.append( "id=" + id );
		ret.append( ", owedBy=" + owedBy );
		ret.append( ", owesTo=" + owesTo );
		ret.append( ", amount=" + amount );
		ret.append( ", currency=" + currency );
		return ret.toString();
	}

}
