/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.dto;

import com.mybillr.app.dao.*;
import com.mybillr.app.factory.*;
import com.mybillr.app.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class News implements Serializable
{
	/** 
	 * This attribute maps to the column id in the news table.
	 */
	protected int id;

	/** 
	 * This attribute represents whether the attribute id has been modified since being read from the database.
	 */
	protected boolean idModified = false;

	/** 
	 * This attribute maps to the column content in the news table.
	 */
	protected String content;

	/** 
	 * This attribute represents whether the attribute content has been modified since being read from the database.
	 */
	protected boolean contentModified = false;

	/** 
	 * This attribute maps to the column dated in the news table.
	 */
	protected Date dated;

	/** 
	 * This attribute represents whether the attribute dated has been modified since being read from the database.
	 */
	protected boolean datedModified = false;

	/**
	 * Method 'News'
	 * 
	 */
	public News()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
		this.idModified = true;
	}

	/** 
	 * Sets the value of idModified
	 */
	public void setIdModified(boolean idModified)
	{
		this.idModified = idModified;
	}

	/** 
	 * Gets the value of idModified
	 */
	public boolean isIdModified()
	{
		return idModified;
	}

	/**
	 * Method 'getContent'
	 * 
	 * @return String
	 */
	public String getContent()
	{
		return content;
	}

	/**
	 * Method 'setContent'
	 * 
	 * @param content
	 */
	public void setContent(String content)
	{
		this.content = content;
		this.contentModified = true;
	}

	/** 
	 * Sets the value of contentModified
	 */
	public void setContentModified(boolean contentModified)
	{
		this.contentModified = contentModified;
	}

	/** 
	 * Gets the value of contentModified
	 */
	public boolean isContentModified()
	{
		return contentModified;
	}

	/**
	 * Method 'getDated'
	 * 
	 * @return Date
	 */
	public Date getDated()
	{
		return dated;
	}

	/**
	 * Method 'setDated'
	 * 
	 * @param dated
	 */
	public void setDated(Date dated)
	{
		this.dated = dated;
		this.datedModified = true;
	}

	/** 
	 * Sets the value of datedModified
	 */
	public void setDatedModified(boolean datedModified)
	{
		this.datedModified = datedModified;
	}

	/** 
	 * Gets the value of datedModified
	 */
	public boolean isDatedModified()
	{
		return datedModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof News)) {
			return false;
		}
		
		final News _cast = (News) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (idModified != _cast.idModified) {
			return false;
		}
		
		if (content == null ? _cast.content != content : !content.equals( _cast.content )) {
			return false;
		}
		
		if (contentModified != _cast.contentModified) {
			return false;
		}
		
		if (dated == null ? _cast.dated != dated : !dated.equals( _cast.dated )) {
			return false;
		}
		
		if (datedModified != _cast.datedModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + (idModified ? 1 : 0);
		if (content != null) {
			_hashCode = 29 * _hashCode + content.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (contentModified ? 1 : 0);
		if (dated != null) {
			_hashCode = 29 * _hashCode + dated.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (datedModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return NewsPk
	 */
	public NewsPk createPk()
	{
		return new NewsPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.app.dto.News: " );
		ret.append( "id=" + id );
		ret.append( ", content=" + content );
		ret.append( ", dated=" + dated );
		return ret.toString();
	}

}
