/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mybillr.app.dao.GroupsDao;
import com.mybillr.app.dto.Groups;
import com.mybillr.app.exceptions.GroupsDaoException;
import com.mybillr.app.factory.GroupsDaoFactory;

public class GroupsDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByUser(0);
		// findWhereIdEquals(0);
		// findWhereNameEquals("");
		// findWhereMemberIdEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			GroupsDao _dao = getGroupsDao();
			Groups _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByUser'
	 * 
	 * @param memberId
	 */
	public static void findByUser(int memberId)
	{
		try {
			GroupsDao _dao = getGroupsDao();
			Groups _result[] = _dao.findByUser(memberId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdEquals'
	 * 
	 * @param id
	 */
	public static void findWhereIdEquals(int id)
	{
		try {
			GroupsDao _dao = getGroupsDao();
			Groups _result[] = _dao.findWhereIdEquals(id);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNameEquals'
	 * 
	 * @param name
	 */
	public static void findWhereNameEquals(String name)
	{
		try {
			GroupsDao _dao = getGroupsDao();
			Groups _result[] = _dao.findWhereNameEquals(name);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereMemberIdEquals'
	 * 
	 * @param memberId
	 */
	public static void findWhereMemberIdEquals(int memberId)
	{
		try {
			GroupsDao _dao = getGroupsDao();
			Groups _result[] = _dao.findWhereMemberIdEquals(memberId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getGroupsDao'
	 * 
	 * @return GroupsDao
	 */
	public static GroupsDao getGroupsDao()
	{
		return GroupsDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Groups dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getId() );
		buf.append( ", " );
		buf.append( dto.getName() );
		buf.append( ", " );
		buf.append( dto.getMemberId() );
		System.out.println( buf.toString() );
	}

}
