/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mybillr.app.dao.ItemizedBillDao;
import com.mybillr.app.dto.ItemizedBill;
import com.mybillr.app.exceptions.ItemizedBillDaoException;
import com.mybillr.app.factory.ItemizedBillDaoFactory;

public class ItemizedBillDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdEquals(0);
		// findWherePaidByEquals("");
		// findWhereItemsEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ItemizedBillDao _dao = getItemizedBillDao();
			ItemizedBill _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdEquals'
	 * 
	 * @param id
	 */
	public static void findWhereIdEquals(int id)
	{
		try {
			ItemizedBillDao _dao = getItemizedBillDao();
			ItemizedBill _result[] = _dao.findWhereIdEquals(id);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePaidByEquals'
	 * 
	 * @param paidBy
	 */
	public static void findWherePaidByEquals(String paidBy)
	{
		try {
			ItemizedBillDao _dao = getItemizedBillDao();
			ItemizedBill _result[] = _dao.findWherePaidByEquals(paidBy);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereItemsEquals'
	 * 
	 * @param items
	 */
	public static void findWhereItemsEquals(String items)
	{
		try {
			ItemizedBillDao _dao = getItemizedBillDao();
			ItemizedBill _result[] = _dao.findWhereItemsEquals(items);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getItemizedBillDao'
	 * 
	 * @return ItemizedBillDao
	 */
	public static ItemizedBillDao getItemizedBillDao()
	{
		return ItemizedBillDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(ItemizedBill dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getId() );
		buf.append( ", " );
		buf.append( dto.getPaidBy() );
		buf.append( ", " );
		buf.append( dto.getItems() );
		System.out.println( buf.toString() );
	}

}
