/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.jdbc;

import com.mybillr.db.dao.*;
import com.mybillr.db.factory.*;
import com.mybillr.db.dto.*;
import com.mybillr.db.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class DebtDaoImpl extends AbstractDAO implements DebtDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id, owed_by, owed_to FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( owed_by, owed_to ) VALUES ( ?, ?)";

	/** 
	 * SQL UPDATE statement for this table
	 */
//	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id = ?, owed_by = ?, owed_to = ? WHERE id = ? AND owed_by = ? AND owed_to = ?";
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET owed_by = ?, owed_to = ? WHERE id = ? AND owed_by = ? AND owed_to = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id = ? AND owed_by = ? AND owed_to = ?";

	/** 
	 * Index of column id
	 */
	protected static final int COLUMN_ID = 1;

	/** 
	 * Index of column owed_by
	 */
	protected static final int COLUMN_OWED_BY = 2;

	/** 
	 * Index of column owed_to
	 */
	protected static final int COLUMN_OWED_TO = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column id
	 */
	protected static final int PK_COLUMN_ID = 1;

	/** 
	 * Index of primary-key column owed_by
	 */
	protected static final int PK_COLUMN_OWED_BY = 2;

	/** 
	 * Index of primary-key column owed_to
	 */
	protected static final int PK_COLUMN_OWED_TO = 3;

	/** 
	 * Inserts a new row in the debt table.
	 */
	public DebtPk insert(Debt dto) throws DebtDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 2;
//			stmt.setInt( index++, dto.getId() );
			stmt.setInt( index++, dto.getOwedBy() );
			stmt.setInt( index++, dto.getOwedTo() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setId( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DebtDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the debt table.
	 */
	public void update(DebtPk pk, Debt dto) throws DebtDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=2;
//			stmt.setInt( index++, dto.getId() );
			stmt.setInt( index++, dto.getOwedBy() );
			stmt.setInt( index++, dto.getOwedTo() );
			stmt.setInt( 4, pk.getId() );
			stmt.setInt( 5, pk.getOwedBy() );
			stmt.setInt( 6, pk.getOwedTo() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DebtDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the debt table.
	 */
	public void delete(DebtPk pk) throws DebtDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getId() );
			stmt.setInt( 2, pk.getOwedBy() );
			stmt.setInt( 3, pk.getOwedTo() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DebtDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the debt table that matches the specified primary-key value.
	 */
	public Debt findByPrimaryKey(DebtPk pk) throws DebtDaoException
	{
		return findByPrimaryKey( pk.getId(), pk.getOwedBy(), pk.getOwedTo() );
	}

	/** 
	 * Returns all rows from the debt table that match the criteria 'id = :id AND owed_by = :owedBy AND owed_to = :owedTo'.
	 */
	public Debt findByPrimaryKey(int id, int owedBy, int owedTo) throws DebtDaoException
	{
		Debt ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id = ? AND owed_by = ? AND owed_to = ?", new Object[] {  new Integer(id),  new Integer(owedBy),  new Integer(owedTo) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the debt table that match the criteria ''.
	 */
	public Debt[] findAll() throws DebtDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id, owed_by, owed_to", null );
	}

	/** 
	 * Returns all rows from the debt table that match the criteria 'owed_by = :owedBy'.
	 */
	public Debt[] findByUser(int owedBy) throws DebtDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE owed_by = ?", new Object[] {  new Integer(owedBy) } );
	}

	/** 
	 * Returns all rows from the debt table that match the criteria 'owed_to = :owedTo'.
	 */
	public Debt[] findByUser2(int owedTo) throws DebtDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE owed_to = ?", new Object[] {  new Integer(owedTo) } );
	}

	/** 
	 * Returns all rows from the debt table that match the criteria 'id = :id'.
	 */
	public Debt[] findWhereIdEquals(int id) throws DebtDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id = ? ORDER BY id", new Object[] {  new Integer(id) } );
	}

	/** 
	 * Returns all rows from the debt table that match the criteria 'owed_by = :owedBy'.
	 */
	public Debt[] findWhereOwedByEquals(int owedBy) throws DebtDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE owed_by = ? ORDER BY owed_by", new Object[] {  new Integer(owedBy) } );
	}

	/** 
	 * Returns all rows from the debt table that match the criteria 'owed_to = :owedTo'.
	 */
	public Debt[] findWhereOwedToEquals(int owedTo) throws DebtDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE owed_to = ? ORDER BY owed_to", new Object[] {  new Integer(owedTo) } );
	}

	/**
	 * Method 'DebtDaoImpl'
	 * 
	 */
	public DebtDaoImpl()
	{
	}

	/**
	 * Method 'DebtDaoImpl'
	 * 
	 * @param userConn
	 */
	public DebtDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "debt";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Debt fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Debt dto = new Debt();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Debt[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Debt dto = new Debt();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Debt ret[] = new Debt[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Debt dto, ResultSet rs) throws SQLException
	{
		dto.setId( rs.getInt( COLUMN_ID ) );
		dto.setOwedBy( rs.getInt( COLUMN_OWED_BY ) );
		dto.setOwedTo( rs.getInt( COLUMN_OWED_TO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Debt dto)
	{
	}

	/** 
	 * Returns all rows from the debt table that match the specified arbitrary SQL statement
	 */
	public Debt[] findByDynamicSelect(String sql, Object[] sqlParams) throws DebtDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DebtDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the debt table that match the specified arbitrary SQL statement
	 */
	public Debt[] findByDynamicWhere(String sql, Object[] sqlParams) throws DebtDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DebtDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
