/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import com.mybillr.db.dao.*;
import com.mybillr.db.factory.*;
import com.mybillr.db.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class AccountActivation implements Serializable
{
	/** 
	 * This attribute maps to the column id in the account_activation table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column user_id in the account_activation table.
	 */
	protected int userId;

	/** 
	 * This attribute maps to the column activation_hash in the account_activation table.
	 */
	protected String activationHash;

	/**
	 * Method 'AccountActivation'
	 * 
	 */
	public AccountActivation()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return int
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
	}

	/**
	 * Method 'getActivationHash'
	 * 
	 * @return String
	 */
	public String getActivationHash()
	{
		return activationHash;
	}

	/**
	 * Method 'setActivationHash'
	 * 
	 * @param activationHash
	 */
	public void setActivationHash(String activationHash)
	{
		this.activationHash = activationHash;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof AccountActivation)) {
			return false;
		}
		
		final AccountActivation _cast = (AccountActivation) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (activationHash == null ? _cast.activationHash != activationHash : !activationHash.equals( _cast.activationHash )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + userId;
		if (activationHash != null) {
			_hashCode = 29 * _hashCode + activationHash.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return AccountActivationPk
	 */
	public AccountActivationPk createPk()
	{
		return new AccountActivationPk(id, userId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.AccountActivation: " );
		ret.append( "id=" + id );
		ret.append( ", userId=" + userId );
		ret.append( ", activationHash=" + activationHash );
		return ret.toString();
	}

}
