/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import com.mybillr.db.dao.*;
import com.mybillr.db.factory.*;
import com.mybillr.db.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class BillDetails implements Serializable
{
	/** 
	 * This attribute maps to the column bill_id in the bill_details table.
	 */
	protected int billId;

	/** 
	 * This attribute maps to the column user_id in the bill_details table.
	 */
	protected int userId;

	/** 
	 * This attribute maps to the column item_name in the bill_details table.
	 */
	protected String itemName;

	/** 
	 * This attribute maps to the column share in the bill_details table.
	 */
	protected long share;

	/** 
	 * This attribute maps to the column amount in the bill_details table.
	 */
	protected long amount;

	/**
	 * Method 'BillDetails'
	 * 
	 */
	public BillDetails()
	{
	}

	/**
	 * Method 'getBillId'
	 * 
	 * @return int
	 */
	public int getBillId()
	{
		return billId;
	}

	/**
	 * Method 'setBillId'
	 * 
	 * @param billId
	 */
	public void setBillId(int billId)
	{
		this.billId = billId;
	}

	/**
	 * Method 'getUserId'
	 * 
	 * @return int
	 */
	public int getUserId()
	{
		return userId;
	}

	/**
	 * Method 'setUserId'
	 * 
	 * @param userId
	 */
	public void setUserId(int userId)
	{
		this.userId = userId;
	}

	/**
	 * Method 'getItemName'
	 * 
	 * @return String
	 */
	public String getItemName()
	{
		return itemName;
	}

	/**
	 * Method 'setItemName'
	 * 
	 * @param itemName
	 */
	public void setItemName(String itemName)
	{
		this.itemName = itemName;
	}

	/**
	 * Method 'getShare'
	 * 
	 * @return long
	 */
	public long getShare()
	{
		return share;
	}

	/**
	 * Method 'setShare'
	 * 
	 * @param share
	 */
	public void setShare(long share)
	{
		this.share = share;
	}

	/**
	 * Method 'getAmount'
	 * 
	 * @return long
	 */
	public long getAmount()
	{
		return amount;
	}

	/**
	 * Method 'setAmount'
	 * 
	 * @param amount
	 */
	public void setAmount(long amount)
	{
		this.amount = amount;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof BillDetails)) {
			return false;
		}
		
		final BillDetails _cast = (BillDetails) _other;
		if (billId != _cast.billId) {
			return false;
		}
		
		if (userId != _cast.userId) {
			return false;
		}
		
		if (itemName == null ? _cast.itemName != itemName : !itemName.equals( _cast.itemName )) {
			return false;
		}
		
		if (share != _cast.share) {
			return false;
		}
		
		if (amount != _cast.amount) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + billId;
		_hashCode = 29 * _hashCode + userId;
		if (itemName != null) {
			_hashCode = 29 * _hashCode + itemName.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (share ^ (share >>> 32));
		_hashCode = 29 * _hashCode + (int) (amount ^ (amount >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return BillDetailsPk
	 */
	public BillDetailsPk createPk()
	{
		return new BillDetailsPk(billId, userId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.BillDetails: " );
		ret.append( "billId=" + billId );
		ret.append( ", userId=" + userId );
		ret.append( ", itemName=" + itemName );
		ret.append( ", share=" + share );
		ret.append( ", amount=" + amount );
		return ret.toString();
	}

}
