/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import com.mybillr.db.dao.*;
import com.mybillr.db.factory.*;
import com.mybillr.db.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Currencies implements Serializable
{
	/** 
	 * This attribute maps to the column id in the currencies table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column name in the currencies table.
	 */
	protected String name;

	/** 
	 * This attribute maps to the column symbol in the currencies table.
	 */
	protected String symbol;

	/** 
	 * This attribute maps to the column rate in the currencies table.
	 */
	protected long rate;

	/**
	 * Method 'Currencies'
	 * 
	 */
	public Currencies()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'getSymbol'
	 * 
	 * @return String
	 */
	public String getSymbol()
	{
		return symbol;
	}

	/**
	 * Method 'setSymbol'
	 * 
	 * @param symbol
	 */
	public void setSymbol(String symbol)
	{
		this.symbol = symbol;
	}

	/**
	 * Method 'getRate'
	 * 
	 * @return long
	 */
	public long getRate()
	{
		return rate;
	}

	/**
	 * Method 'setRate'
	 * 
	 * @param rate
	 */
	public void setRate(long rate)
	{
		this.rate = rate;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Currencies)) {
			return false;
		}
		
		final Currencies _cast = (Currencies) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (symbol == null ? _cast.symbol != symbol : !symbol.equals( _cast.symbol )) {
			return false;
		}
		
		if (rate != _cast.rate) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		if (symbol != null) {
			_hashCode = 29 * _hashCode + symbol.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) (rate ^ (rate >>> 32));
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CurrenciesPk
	 */
	public CurrenciesPk createPk()
	{
		return new CurrenciesPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.Currencies: " );
		ret.append( "id=" + id );
		ret.append( ", name=" + name );
		ret.append( ", symbol=" + symbol );
		ret.append( ", rate=" + rate );
		return ret.toString();
	}

}
