/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import com.mybillr.db.dao.*;
import com.mybillr.db.factory.*;
import com.mybillr.db.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Debt implements Serializable
{
	/** 
	 * This attribute maps to the column id in the debt table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column owed_by in the debt table.
	 */
	protected int owedBy;

	/** 
	 * This attribute maps to the column owed_to in the debt table.
	 */
	protected int owedTo;

	/**
	 * Method 'Debt'
	 * 
	 */
	public Debt()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getOwedBy'
	 * 
	 * @return int
	 */
	public int getOwedBy()
	{
		return owedBy;
	}

	/**
	 * Method 'setOwedBy'
	 * 
	 * @param owedBy
	 */
	public void setOwedBy(int owedBy)
	{
		this.owedBy = owedBy;
	}

	/**
	 * Method 'getOwedTo'
	 * 
	 * @return int
	 */
	public int getOwedTo()
	{
		return owedTo;
	}

	/**
	 * Method 'setOwedTo'
	 * 
	 * @param owedTo
	 */
	public void setOwedTo(int owedTo)
	{
		this.owedTo = owedTo;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Debt)) {
			return false;
		}
		
		final Debt _cast = (Debt) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (owedBy != _cast.owedBy) {
			return false;
		}
		
		if (owedTo != _cast.owedTo) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + owedBy;
		_hashCode = 29 * _hashCode + owedTo;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DebtPk
	 */
	public DebtPk createPk()
	{
		return new DebtPk(id, owedBy, owedTo);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.Debt: " );
		ret.append( "id=" + id );
		ret.append( ", owedBy=" + owedBy );
		ret.append( ", owedTo=" + owedTo );
		return ret.toString();
	}

}
