/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import com.mybillr.db.dao.*;
import com.mybillr.db.factory.*;
import com.mybillr.db.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class EmailsSent implements Serializable
{
	/** 
	 * This attribute maps to the column id in the emails_sent table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column sender_id in the emails_sent table.
	 */
	protected int senderId;

	/** 
	 * This attribute maps to the column receiver_id in the emails_sent table.
	 */
	protected int receiverId;

	/** 
	 * This attribute maps to the column subject in the emails_sent table.
	 */
	protected String subject;

	/** 
	 * This attribute maps to the column content in the emails_sent table.
	 */
	protected String content;

	/**
	 * Method 'EmailsSent'
	 * 
	 */
	public EmailsSent()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getSenderId'
	 * 
	 * @return int
	 */
	public int getSenderId()
	{
		return senderId;
	}

	/**
	 * Method 'setSenderId'
	 * 
	 * @param senderId
	 */
	public void setSenderId(int senderId)
	{
		this.senderId = senderId;
	}

	/**
	 * Method 'getReceiverId'
	 * 
	 * @return int
	 */
	public int getReceiverId()
	{
		return receiverId;
	}

	/**
	 * Method 'setReceiverId'
	 * 
	 * @param receiverId
	 */
	public void setReceiverId(int receiverId)
	{
		this.receiverId = receiverId;
	}

	/**
	 * Method 'getSubject'
	 * 
	 * @return String
	 */
	public String getSubject()
	{
		return subject;
	}

	/**
	 * Method 'setSubject'
	 * 
	 * @param subject
	 */
	public void setSubject(String subject)
	{
		this.subject = subject;
	}

	/**
	 * Method 'getContent'
	 * 
	 * @return String
	 */
	public String getContent()
	{
		return content;
	}

	/**
	 * Method 'setContent'
	 * 
	 * @param content
	 */
	public void setContent(String content)
	{
		this.content = content;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EmailsSent)) {
			return false;
		}
		
		final EmailsSent _cast = (EmailsSent) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (senderId != _cast.senderId) {
			return false;
		}
		
		if (receiverId != _cast.receiverId) {
			return false;
		}
		
		if (subject == null ? _cast.subject != subject : !subject.equals( _cast.subject )) {
			return false;
		}
		
		if (content == null ? _cast.content != content : !content.equals( _cast.content )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + senderId;
		_hashCode = 29 * _hashCode + receiverId;
		if (subject != null) {
			_hashCode = 29 * _hashCode + subject.hashCode();
		}
		
		if (content != null) {
			_hashCode = 29 * _hashCode + content.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EmailsSentPk
	 */
	public EmailsSentPk createPk()
	{
		return new EmailsSentPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.EmailsSent: " );
		ret.append( "id=" + id );
		ret.append( ", senderId=" + senderId );
		ret.append( ", receiverId=" + receiverId );
		ret.append( ", subject=" + subject );
		ret.append( ", content=" + content );
		return ret.toString();
	}

}
