/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.dto;

import com.mybillr.db.dao.*;
import com.mybillr.db.factory.*;
import com.mybillr.db.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class News implements Serializable
{
	/** 
	 * This attribute maps to the column id in the news table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column title in the news table.
	 */
	protected String title;

	/** 
	 * This attribute maps to the column content in the news table.
	 */
	protected String content;

	/**
	 * Method 'News'
	 * 
	 */
	public News()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getTitle'
	 * 
	 * @return String
	 */
	public String getTitle()
	{
		return title;
	}

	/**
	 * Method 'setTitle'
	 * 
	 * @param title
	 */
	public void setTitle(String title)
	{
		this.title = title;
	}

	/**
	 * Method 'getContent'
	 * 
	 * @return String
	 */
	public String getContent()
	{
		return content;
	}

	/**
	 * Method 'setContent'
	 * 
	 * @param content
	 */
	public void setContent(String content)
	{
		this.content = content;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof News)) {
			return false;
		}
		
		final News _cast = (News) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (title == null ? _cast.title != title : !title.equals( _cast.title )) {
			return false;
		}
		
		if (content == null ? _cast.content != content : !content.equals( _cast.content )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (title != null) {
			_hashCode = 29 * _hashCode + title.hashCode();
		}
		
		if (content != null) {
			_hashCode = 29 * _hashCode + content.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return NewsPk
	 */
	public NewsPk createPk()
	{
		return new NewsPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mybillr.db.dto.News: " );
		ret.append( "id=" + id );
		ret.append( ", title=" + title );
		ret.append( ", content=" + content );
		return ret.toString();
	}

}
