/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mybillr.app.dao.EmailSentDao;
import com.mybillr.app.dto.EmailSent;
import com.mybillr.app.exceptions.EmailSentDaoException;
import com.mybillr.app.factory.EmailSentDaoFactory;

public class EmailSentDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdEquals(0);
		// findWhereFromEquals("");
		// findWhereToEquals("");
		// findWhereSubjectEquals("");
		// findWhereMessageEquals("");
		// findWhereSentOnEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			EmailSentDao _dao = getEmailSentDao();
			EmailSent _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdEquals'
	 * 
	 * @param id
	 */
	public static void findWhereIdEquals(int id)
	{
		try {
			EmailSentDao _dao = getEmailSentDao();
			EmailSent _result[] = _dao.findWhereIdEquals(id);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFromEquals'
	 * 
	 * @param from
	 */
	public static void findWhereFromEquals(String from)
	{
		try {
			EmailSentDao _dao = getEmailSentDao();
			EmailSent _result[] = _dao.findWhereFromEquals(from);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereToEquals'
	 * 
	 * @param to
	 */
	public static void findWhereToEquals(String to)
	{
		try {
			EmailSentDao _dao = getEmailSentDao();
			EmailSent _result[] = _dao.findWhereToEquals(to);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSubjectEquals'
	 * 
	 * @param subject
	 */
	public static void findWhereSubjectEquals(String subject)
	{
		try {
			EmailSentDao _dao = getEmailSentDao();
			EmailSent _result[] = _dao.findWhereSubjectEquals(subject);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereMessageEquals'
	 * 
	 * @param message
	 */
	public static void findWhereMessageEquals(String message)
	{
		try {
			EmailSentDao _dao = getEmailSentDao();
			EmailSent _result[] = _dao.findWhereMessageEquals(message);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSentOnEquals'
	 * 
	 * @param sentOn
	 */
	public static void findWhereSentOnEquals(Date sentOn)
	{
		try {
			EmailSentDao _dao = getEmailSentDao();
			EmailSent _result[] = _dao.findWhereSentOnEquals(sentOn);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getEmailSentDao'
	 * 
	 * @return EmailSentDao
	 */
	public static EmailSentDao getEmailSentDao()
	{
		return EmailSentDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(EmailSent dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getId() );
		buf.append( ", " );
		buf.append( dto.getFrom() );
		buf.append( ", " );
		buf.append( dto.getTo() );
		buf.append( ", " );
		buf.append( dto.getSubject() );
		buf.append( ", " );
		buf.append( dto.getMessage() );
		buf.append( ", " );
		buf.append( dto.getSentOn() );
		System.out.println( buf.toString() );
	}

}
