/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mybillr.app.dao.FriendsDao;
import com.mybillr.app.dto.Friends;
import com.mybillr.app.exceptions.FriendsDaoException;
import com.mybillr.app.factory.FriendsDaoFactory;

public class FriendsDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByUser(0);
		// findByUser2(0);
		// findWhereUserIdEquals(0);
		// findWhereFriendIdEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			FriendsDao _dao = getFriendsDao();
			Friends _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByUser'
	 * 
	 * @param userId
	 */
	public static void findByUser(int userId)
	{
		try {
			FriendsDao _dao = getFriendsDao();
			Friends _result[] = _dao.findByUser(userId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByUser2'
	 * 
	 * @param friendId
	 */
	public static void findByUser2(int friendId)
	{
		try {
			FriendsDao _dao = getFriendsDao();
			Friends _result[] = _dao.findByUser2(friendId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUserIdEquals'
	 * 
	 * @param userId
	 */
	public static void findWhereUserIdEquals(int userId)
	{
		try {
			FriendsDao _dao = getFriendsDao();
			Friends _result[] = _dao.findWhereUserIdEquals(userId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFriendIdEquals'
	 * 
	 * @param friendId
	 */
	public static void findWhereFriendIdEquals(int friendId)
	{
		try {
			FriendsDao _dao = getFriendsDao();
			Friends _result[] = _dao.findWhereFriendIdEquals(friendId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getFriendsDao'
	 * 
	 * @return FriendsDao
	 */
	public static FriendsDao getFriendsDao()
	{
		return FriendsDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Friends dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getUserId() );
		buf.append( ", " );
		buf.append( dto.getFriendId() );
		System.out.println( buf.toString() );
	}

}
