/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mybillr.app.dao.NewsDao;
import com.mybillr.app.dto.News;
import com.mybillr.app.exceptions.NewsDaoException;
import com.mybillr.app.factory.NewsDaoFactory;

public class NewsDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdEquals(0);
		// findWhereContentEquals("");
		// findWhereDatedEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			NewsDao _dao = getNewsDao();
			News _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdEquals'
	 * 
	 * @param id
	 */
	public static void findWhereIdEquals(int id)
	{
		try {
			NewsDao _dao = getNewsDao();
			News _result[] = _dao.findWhereIdEquals(id);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereContentEquals'
	 * 
	 * @param content
	 */
	public static void findWhereContentEquals(String content)
	{
		try {
			NewsDao _dao = getNewsDao();
			News _result[] = _dao.findWhereContentEquals(content);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDatedEquals'
	 * 
	 * @param dated
	 */
	public static void findWhereDatedEquals(Date dated)
	{
		try {
			NewsDao _dao = getNewsDao();
			News _result[] = _dao.findWhereDatedEquals(dated);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getNewsDao'
	 * 
	 * @return NewsDao
	 */
	public static NewsDao getNewsDao()
	{
		return NewsDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(News dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getId() );
		buf.append( ", " );
		buf.append( dto.getContent() );
		buf.append( ", " );
		buf.append( dto.getDated() );
		System.out.println( buf.toString() );
	}

}
