/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mybillr.app.dao.UserDao;
import com.mybillr.app.dto.User;
import com.mybillr.app.exceptions.UserDaoException;
import com.mybillr.app.factory.UserDaoFactory;

public class UserDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdEquals(0);
		// findWhereFnameEquals("");
		// findWhereLnameEquals("");
		// findWhereEmailEquals("");
		// findWherePhoneEquals(0);
		// findWhereSaltEquals("");
		// findWherePasswordEquals("");
		// findWhereCreatedOnEquals(null);
		// findWhereUpdatedOnEquals(null);
		// findWhereLastLoggedEquals(null);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdEquals'
	 * 
	 * @param id
	 */
	public static void findWhereIdEquals(int id)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWhereIdEquals(id);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereFnameEquals'
	 * 
	 * @param fname
	 */
	public static void findWhereFnameEquals(String fname)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWhereFnameEquals(fname);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLnameEquals'
	 * 
	 * @param lname
	 */
	public static void findWhereLnameEquals(String lname)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWhereLnameEquals(lname);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEmailEquals'
	 * 
	 * @param email
	 */
	public static void findWhereEmailEquals(String email)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWhereEmailEquals(email);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePhoneEquals'
	 * 
	 * @param phone
	 */
	public static void findWherePhoneEquals(int phone)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWherePhoneEquals(phone);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSaltEquals'
	 * 
	 * @param salt
	 */
	public static void findWhereSaltEquals(String salt)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWhereSaltEquals(salt);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePasswordEquals'
	 * 
	 * @param password
	 */
	public static void findWherePasswordEquals(String password)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWherePasswordEquals(password);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCreatedOnEquals'
	 * 
	 * @param createdOn
	 */
	public static void findWhereCreatedOnEquals(Date createdOn)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWhereCreatedOnEquals(createdOn);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUpdatedOnEquals'
	 * 
	 * @param updatedOn
	 */
	public static void findWhereUpdatedOnEquals(Date updatedOn)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWhereUpdatedOnEquals(updatedOn);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLastLoggedEquals'
	 * 
	 * @param lastLogged
	 */
	public static void findWhereLastLoggedEquals(Date lastLogged)
	{
		try {
			UserDao _dao = getUserDao();
			User _result[] = _dao.findWhereLastLoggedEquals(lastLogged);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getUserDao'
	 * 
	 * @return UserDao
	 */
	public static UserDao getUserDao()
	{
		return UserDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(User dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getId() );
		buf.append( ", " );
		buf.append( dto.getFname() );
		buf.append( ", " );
		buf.append( dto.getLname() );
		buf.append( ", " );
		buf.append( dto.getEmail() );
		buf.append( ", " );
		buf.append( dto.getPhone() );
		buf.append( ", " );
		buf.append( dto.getSalt() );
		buf.append( ", " );
		buf.append( dto.getPassword() );
		buf.append( ", " );
		buf.append( dto.getCreatedOn() );
		buf.append( ", " );
		buf.append( dto.getUpdatedOn() );
		buf.append( ", " );
		buf.append( dto.getLastLogged() );
		System.out.println( buf.toString() );
	}

}
