/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.db.factory;

import java.sql.Connection;
import com.mybillr.db.dao.*;
import com.mybillr.db.jdbc.*;

public class Table1DaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return Table1Dao
	 */
	public static Table1Dao create()
	{
		return new Table1DaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return Table1Dao
	 */
	public static Table1Dao create(Connection conn)
	{
		return new Table1DaoImpl( conn );
	}

}
