/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mybillr.app.factory;

import java.sql.Connection;
import com.mybillr.app.dao.*;
import com.mybillr.app.jdbc.*;

public class EmailSentDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return EmailSentDao
	 */
	public static EmailSentDao create()
	{
		return new EmailSentDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return EmailSentDao
	 */
	public static EmailSentDao create(Connection conn)
	{
		return new EmailSentDaoImpl( conn );
	}

}
